name: dart_task_application
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  intl: ^0.19.0
  url_launcher: ^6.2.4
  io: ^1.0.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
